### ISSUE TITLE
Rewriting documentation

### ISSUE THREAD

**Issue by Phoenixx19** [TeamNexile/jk-workshop-docs#1]
- [x] Home
- [x] Getting started
  - [x] Requirements
  - [x] Guidelines
  - [x] Level: First Steps
  - [x] Skin: First Steps
- [x] Tools
  - [x] Content packing tools
    - [x] Fast XNB Builder
    - [x] XNBCLI
    - [x] TConvert
    - [x] Monogame Pipeline
    - [x] PNG to XNB
  - [x] Level helping tools
    - [x] Hitbox2Screens
    - [x] JumpKingManager
- [x] Level Making
  - [x] Hitboxes
  - [x] Blocks
  - [x] Screens
  - [x] Props
    - [x] World Items
    - [x] Hidden Walls
    - [x] NPCs
    - [x] Merchants
    - [x] Ravens
    - [x] Messages
  - [x] King
  - [x] GUI
  - [x] Audio
  - [x] Particles
  - [x] Tips
- [x] Skin Making
- [x] Publishing
- [x] Updating
- [x] Credits
- [x] Porting content from JK+ [external]

**Comment by ThomasOfTawny** [comment]
Notes:

- [x] Getting started: Maybe add "and use" after creation in the text under "What is the Workshop?"
- [x] Getting started has a link to "Sample custom level" that currently leads nowhere
- [x] Rules and guidelines: Remove the "don't" under the header, pretty sure it is the opposite of the intended message right now
- [x] Guidelines: Mentioned before I'm pretty sure but "won't endorse" -> "is unlikely to endorse" and "won't" -> "do not" under the "Polished levels" section 
- [x] "Tips" is not in the table of contents
- [x] Publishing: Same change as with guidelines with phrasing
- [x] Publishing: Looks like there's some WIP content, is the documentation actually done then for the section?
- [x] Porting content: Link does not work

**Comment by Phoenixx19** [comment]
Done.

**Comment by ThomasOfTawny** [comment]
Improvements: 

- [x] **Level Making:** Add a "File Types" subpage under "Level Making" listing all file types used for level making with explanation of what they do. Explain XML and XNB on an entry level
- [x] **ALL:** Clean up/cut text that has personal flavour in them (only informative text should remain) **WE WILL DO THIS TASK AS A LIVE COLLABORATION**
- [x] **Hitboxes:** Swap out the picture in "Hitboxes" with a similar but exclude "fake block" in the picture. Add image text explaining that block types will be explained in the "Blocks" subpage
